// Code generated by mockery v1.0.0. DO NOT EDIT.

package creatingmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateCounter provides a mock function with given fields: ctx, name, belongsTo
func (_m *Service) CreateCounter(ctx context.Context, name string, belongsTo string) error {
	ret := _m.Called(ctx, name, belongsTo)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, belongsTo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
