// Code generated by mockery v1.0.0. DO NOT EDIT.

package fetchingmock

import context "context"
import counters "github.com/friendsofgo/workshop-microservices/internal"

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FetchAllCountersByUser provides a mock function with given fields: ctx, belongsTo
func (_m *Service) FetchAllCountersByUser(ctx context.Context, belongsTo string) ([]counters.Counter, error) {
	ret := _m.Called(ctx, belongsTo)

	var r0 []counters.Counter
	if rf, ok := ret.Get(0).(func(context.Context, string) []counters.Counter); ok {
		r0 = rf(ctx, belongsTo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]counters.Counter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, belongsTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
